services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mlops-logistic-regression-api
    container_name: mlops-logistic-regression-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./mlruns:/app/mlruns
      - ./configs:/app/configs

  prometheus:
    image: prom/prometheus:latest
    container_name: mlops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api