apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-api-data-pvc
  namespace: mlops-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-api-reports-pvc
  namespace: mlops-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-api-mlruns-pvc
  namespace: mlops-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi