apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api
  namespace: mlops-local
  labels:
    app: mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
        - name: mlops-api
          image: mlops-logistic-regression-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONPATH
              value: /app/src
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - name: api-config
              mountPath: /app/configs/config.yaml
              subPath: config.yaml
            - name: api-data
              mountPath: /app/data
            - name: api-reports
              mountPath: /app/reports
            - name: api-mlruns
              mountPath: /app/mlruns
      volumes:
        - name: api-config
          configMap:
            name: mlops-api-config
        - name: api-data
          persistentVolumeClaim:
            claimName: mlops-api-data-pvc
        - name: api-reports
          persistentVolumeClaim:
            claimName: mlops-api-reports-pvc
        - name: api-mlruns
          persistentVolumeClaim:
            claimName: mlops-api-mlruns-pvc