apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: mlops-local
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:latest
          command:
            - /otelcol
            - --config=/etc/otel-collector-config.yml
          ports:
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config.yml
              subPath: otel-collector-config.yml
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config