apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mlops-local
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: mlops-api
        metrics_path: /metrics
        static_configs:
          - targets:
              - mlops-api-service:8000